### ISSUE TITLE
Fix the URL for sending logs

### ISSUE THREAD

**Issue by olofjohansson** [logentries/le_php#15]
The constants defined in LeLogger.php has been set to `api.logentries.com`, but the documentation (https://logentries.com/doc/input-token/) says that the address should be `data.logentries.com`.

I guess that this needs to be changed, both for TCP and TLS?

**Comment by olofjohansson** [comment]
Correction: The only address that needs to be changed is the one for TCP. TLS should remain as api.logentries.com.

I verified this by sending logs via TCP to api.logentries.com, but the logs weren't received. It worked if I changed it to data.logentries.com.

**Comment by olofjohansson** [comment]
I've implemented this in https://github.com/logentries/le_php/commit/4cb76923735371806f11dfac267e64f2e77775ef, for reference.

**Comment by gearoidof** [comment]
Hi Olaf, sorry for delay in this, we no longer maintain this project. However, I'm going to implement your suggestion now!
 Both api.logentries.com & data.logentries.com will work, but data.logentries.com is our preferred endpoint.

**Comment by gearoidof** [comment]
Oh apologies, you already have this implemented, I'm going to close this and discuss everything in your PR
